### PR TITLE
Feature - 3304 - tW GroupData, ContextId & quote from UGNT

### PR DESCRIPTION
**Pull request by richmahn**
See:

https://github.com/unfoldingWord-dev/translationCore/issues/3304

Adds a script in scripts/buildTw.js which is called by running `npm run build-ugnt-tw` that will pass the proper arguments for generating the tW from the UGNT.

Needs review of the generated files which are in resources/grc/translationHelps/translationWords/v0

---
This change is [Reviewable](https://reviewable.io/reviews/translationcoreapps/tc_resources/16)

### CODE REVIEW

**Comment by mannycolon** [comment]
Reviewed 2 of 1844 files at r2, 1846 of 1846 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[__tests__/fixtures/tw_ugnt_test/resources.zip, line 0 at r3](https://reviewable.io:443/reviews/translationcoreapps/tc_resources/16#-L5BV5l1kgQhM7mhnVSJ:-L5BV5l2JPBKV97H2NWw:bivgdw5) ([raw file](https://github.com/translationcoreapps/tc_resources/blob/555753bd4ef95073f05f3cbca7c91907c715d3c3/__tests__/fixtures/tw_ugnt_test/resources.zip#L0)):*
I dont think we need this file, do we?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/tc_resources/16)*

**Comment by klappy** [comment]
*[__tests__/fixtures/tw_ugnt_test/resources.zip, line  at r3](https://reviewable.io:443/reviews/translationcoreapps/tc_resources/16#-L5BV5l1kgQhM7mhnVSJ:-L5EXqBG80BZ6mRLiCNj:b3571ib) ([raw file](https://github.com/translationcoreapps/tc_resources/blob/555753bd4ef95073f05f3cbca7c91907c715d3c3/__tests__/fixtures/tw_ugnt_test/resources.zip#L)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

I dont think we need this file, do we?
</blockquote></details>

@mannycolon I believe the .zip file was added previously for including a ton of files for tests and maybe it was zipped to prevent hundreds of small files from being in the repo. however that does cause a new problem of repo bloat even more quickly as small changes can’t be tracked and the entire .zip file has to change when updated instead of just a few bytes at a time.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/tc_resources/16)*

**Comment by klappy** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/tc_resources/16#-:-L5EvrHegQEk73UaKZ8F:bnfp4nl)*

**Comment by RoyalSix** [comment]
Reviewed 1 of 1844 files at r2, 117 of 1846 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[__tests__/twHelpers.test.js, line 42 at r3](https://reviewable.io:443/reviews/translationcoreapps/tc_resources/16#-L5BW24gKktHXOHaau09:-L5BW24hA4Xc_hXjxr2I:bjloop4) ([raw file](https://github.com/translationcoreapps/tc_resources/blob/555753bd4ef95073f05f3cbca7c91907c715d3c3/__tests__/twHelpers.test.js#L42)):*
> ```JavaScript
>       const json = JSON.parse(fs.readFileSync(inChristJsonFile));
>       expect(json).toMatchSnapshot();
>       console.log('tW processing completed!');
> ```

console.log

---

*[helpers/twHelpers.js, line 40 at r3](https://reviewable.io:443/reviews/translationcoreapps/tc_resources/16#-L5BYzf4c3_ODknawXd2:-L5BYzf4c3_ODknawXd3:b2sh2f7) ([raw file](https://github.com/translationcoreapps/tc_resources/blob/555753bd4ef95073f05f3cbca7c91907c715d3c3/helpers/twHelpers.js#L40)):*
> ```JavaScript
> function convertBookVerseObjectsToTwData(bookName) {
>   const bookId = getbookId(bookName);
>   twData = {};
> ```

is this being used in this namespace? Where is it getting written to?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/tc_resources/16)*

**Comment by RoyalSix** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[helpers/twHelpers.js, line 31 at r3](https://reviewable.io:443/reviews/translationcoreapps/tc_resources/16#-L5F0dhxBRLWdRlntQQR:-L5F0dhxBRLWdRlntQQS:b-6tm0at) ([raw file](https://github.com/translationcoreapps/tc_resources/blob/555753bd4ef95073f05f3cbca7c91907c715d3c3/helpers/twHelpers.js#L31)):*
> ```JavaScript
>     convertBookVerseObjectsToTwData(bookName);
>   });
>   resolve(true);
> ```

Since this is async do you need to use a callback? I think you could just return true

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/tc_resources/16)*

**Comment by richmahn** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[__tests__/fixtures/tw_ugnt_test/resources.zip, line  at r3](https://reviewable.io:443/reviews/translationcoreapps/tc_resources/16#-L5BV5l1kgQhM7mhnVSJ:-L5FZ1wTamrJB1HGwVZL:b-ipnhgd) ([raw file](https://github.com/translationcoreapps/tc_resources/blob/555753bd4ef95073f05f3cbca7c91907c715d3c3/__tests__/fixtures/tw_ugnt_test/resources.zip#L)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

@mannycolon I believe the .zip file was added previously for including a ton of files for tests and maybe it was zipped to prevent hundreds of small files from being in the repo. however that does cause a new problem of repo bloat even more quickly as small changes can’t be tracked and the entire .zip file has to change when updated instead of just a few bytes at a time.
</blockquote></details>

This zip file is added by me for my tests, so that I have a frozen UGNT VerseObject file structure to test the tWs to be generated from. I could use the actual resources/grc/bibles/ugnt/v0, but was always taught/told to use data that is static thus is fixtures, so code could be tested on the expected data.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/tc_resources/16)*

**Comment by richmahn** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[helpers/twHelpers.js, line 31 at r3](https://reviewable.io:443/reviews/translationcoreapps/tc_resources/16#-L5F0dhxBRLWdRlntQQR:-L5FZaqfDGvmFQmbrhht:b-gmv30i) ([raw file](https://github.com/translationcoreapps/tc_resources/blob/555753bd4ef95073f05f3cbca7c91907c715d3c3/helpers/twHelpers.js#L31)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Since this is async do you need to use a callback? I think you could just return true
</blockquote></details>

Yes, will change. I copied too much from ugntHelpers.test.js which required wait time.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/tc_resources/16)*

**Comment by richmahn** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[helpers/twHelpers.js, line 40 at r3](https://reviewable.io:443/reviews/translationcoreapps/tc_resources/16#-L5BYzf4c3_ODknawXd2:-L5FZogLFYOW_oNKCkzZ:bvveshm) ([raw file](https://github.com/translationcoreapps/tc_resources/blob/555753bd4ef95073f05f3cbca7c91907c715d3c3/helpers/twHelpers.js#L40)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

is this being used in this namespace? Where is it getting written to?
</blockquote></details>

Kind of a global variable. Went back and forth with twData and groupData being passed all over the place, but then had it reset for each iteration.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/tc_resources/16)*

**Comment by richmahn** [comment]
Review status: 926 of 927 files reviewed at latest revision, 4 unresolved discussions.

---

*[__tests__/twHelpers.test.js, line 42 at r3](https://reviewable.io:443/reviews/translationcoreapps/tc_resources/16#-L5BW24gKktHXOHaau09:-L5FdreNWmQHhnFMcYlg:btwm7zi) ([raw file](https://github.com/translationcoreapps/tc_resources/blob/555753bd4ef95073f05f3cbca7c91907c715d3c3/__tests__/twHelpers.test.js#L42)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

console.log
</blockquote></details>

Right, not the best in the test. Should I remove from ugntHelpers.test.js (Bruce's) too?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/tc_resources/16)*

**Comment by richmahn** [comment]
Review status: 922 of 930 files reviewed at latest revision, 4 unresolved discussions.

---

*[__tests__/fixtures/tw_ugnt_test/resources.zip, line  at r3](https://reviewable.io:443/reviews/translationcoreapps/tc_resources/16#-L5BV5l1kgQhM7mhnVSJ:-L5FhlfwPccXc59Rf6_t:b-2s3k23) ([raw file](https://github.com/translationcoreapps/tc_resources/blob/555753bd4ef95073f05f3cbca7c91907c715d3c3/__tests__/fixtures/tw_ugnt_test/resources.zip#L)):*
<details><summary><i>Previously, richmahn (Richard Mahn) wrote…</i></summary><blockquote>

This zip file is added by me for my tests, so that I have a frozen UGNT VerseObject file structure to test the tWs to be generated from. I could use the actual resources/grc/bibles/ugnt/v0, but was always taught/told to use data that is static thus is fixtures, so code could be tested on the expected data.
</blockquote></details>

Removed this. I assume testing from the actual UGNT resource is best, but I don't write out to the actual tw directory, but a temp dir.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/tc_resources/16)*

**Comment by mannycolon** [comment]
Reviewed 1 of 1844 files at r2, 9 of 9 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/tc_resources/16)*

**Pull request merged**
