### PR TITLE
Fix casing issues of BHP

### PR DESCRIPTION
**Pull request by klappy**
This change is [Reviewable](https://reviewable.io/reviews/translationcoreapps/tc_resources/9)

### CODE REVIEW

**Comment by mannycolon** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[resources/grc/bibles/bhp/v0/tit/1.json, line 1111 at r1](https://reviewable.io:443/reviews/translationcoreapps/tc_resources/9#-Kw1LfBAjOhM8JDtTw2C:-Kw1LfBAjOhM8JDtTw2D:blbafo6) ([raw file](https://github.com/translationcoreapps/tc_resources/blob/75bc16bb077d86ef05e890ba94290578d6658d44/resources/grc/bibles/bhp/v0/tit/1.json#L1111)):*
> ```JSON
>       "morph": "Gr,N,,,,,NMS,"
>     },
>     "“",
> ```

is this expected?

---

*[resources/grc/bibles/bhp/v0/tit/3.json, line 677 at r1](https://reviewable.io:443/reviews/translationcoreapps/tc_resources/9#-Kw1Ls23kMJpT0U0O53s:-Kw1Ls23kMJpT0U0O53t:b-f7o7lt) ([raw file](https://github.com/translationcoreapps/tc_resources/blob/75bc16bb077d86ef05e890ba94290578d6658d44/resources/grc/bibles/bhp/v0/tit/3.json#L677)):*
> ```JSON
>       "morph": "Gr,VINPM,,,,,"
>     },
>     "“",
> ```

is this also expected?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/tc_resources/9)*

**Comment by klappy** [comment]
*[resources/grc/bibles/bhp/v0/tit/1.json, line 1111 at r1](https://reviewable.io:443/reviews/translationcoreapps/tc_resources/9#-Kw1LfBAjOhM8JDtTw2C:-Kw1NIdeSheLM-lXSwMQ:b-77xwke) ([raw file](https://github.com/translationcoreapps/tc_resources/blob/75bc16bb077d86ef05e890ba94290578d6658d44/resources/grc/bibles/bhp/v0/tit/1.json#L1111)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

is this expected?
</blockquote></details>

Good catch. Long term we have to find a way to preserve punctuation that we are now ignoring. Looks like this is a case where the punct got in early.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/tc_resources/9)*

**Comment by klappy** [comment]
*[resources/grc/bibles/bhp/v0/tit/3.json, line 677 at r1](https://reviewable.io:443/reviews/translationcoreapps/tc_resources/9#-Kw1Ls23kMJpT0U0O53s:-Kw1OWPUsyCYYCS7cEYy:biiwdx1) ([raw file](https://github.com/translationcoreapps/tc_resources/blob/75bc16bb077d86ef05e890ba94290578d6658d44/resources/grc/bibles/bhp/v0/tit/3.json#L677)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

is this also expected?
</blockquote></details>

I'm removing these and pushing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/tc_resources/9)*

**Comment by klappy** [comment]
*[resources/grc/bibles/bhp/v0/tit/1.json, line 1111 at r1](https://reviewable.io:443/reviews/translationcoreapps/tc_resources/9#-Kw1LfBAjOhM8JDtTw2C:-Kw1PXHw8YU6Ryp3iSR5:b-896fix) ([raw file](https://github.com/translationcoreapps/tc_resources/blob/75bc16bb077d86ef05e890ba94290578d6658d44/resources/grc/bibles/bhp/v0/tit/1.json#L1111)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Good catch. Long term we have to find a way to preserve punctuation that we are now ignoring. Looks like this is a case where the punct got in early.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/tc_resources/9)*

**Comment by klappy** [comment]
*[resources/grc/bibles/bhp/v0/tit/3.json, line 677 at r1](https://reviewable.io:443/reviews/translationcoreapps/tc_resources/9#-Kw1Ls23kMJpT0U0O53s:-Kw1PZAx6ek4zvJ__Mki:b-896fix) ([raw file](https://github.com/translationcoreapps/tc_resources/blob/75bc16bb077d86ef05e890ba94290578d6658d44/resources/grc/bibles/bhp/v0/tit/3.json#L677)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

I'm removing these and pushing.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/tc_resources/9)*

**Comment by mannycolon** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/tc_resources/9#-:-Kw5kYVCLww34Q7MY8JZ:bnfp4nl)*

**Pull request merged**
