### PR TITLE
Feature/3104/Convert BHP to chapter files.

### PR DESCRIPTION
**Pull request by PhotoNomad0**
## This PR Addresses

Adding a helper to convert a usfm file from path to json chapter files given a path.
Also added a script to download BHP files and convert to chapter files: `./script/bhpParse.js`.  See instructions to run in that file.  Currently the format of the bhp usfm files are being changed from using key `strongs` to using `strong`.  So do not generate and commit new bhp files until tC has been updated.

## To Test this PR

- Run `npm install` inside `tC_resources` path to install node_modules
- Run `npm test` to verify that the tests pass to ensure functionality

---
This change is [Reviewable](https://reviewable.io/reviews/translationcoreapps/tc_resources/12)

### CODE REVIEW

**Comment by PhotoNomad0** [comment]
Working on fixing the unit tests.

**Comment by mannycolon** [comment]
Reviewed 5 of 6 files at r1, 1 of 2 files at r2, 263 of 263 files at r3, 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[__tests__/bhpToJsonParse.test.js, line 6 at r4](https://reviewable.io:443/reviews/translationcoreapps/tc_resources/12#-Kz4cWxnU3JixRqVC_GU:-Kz4cWxnU3JixRqVC_GV:bp58gzj) ([raw file](https://github.com/translationcoreapps/tc_resources/blob/d540220ca59b5f970caca4da1e52b7316e0db0fd/__tests__/bhpToJsonParse.test.js#L6)):*
> ```JavaScript
>  *
>  *    To run script:
>  *    * remove `.skip` on describe
> ```

we may want to create a mock API to test these methods so that we don't have to rely on removing .skip

---

*[__tests__/bhpToJsonParse.test.js, line 11 at r4](https://reviewable.io:443/reviews/translationcoreapps/tc_resources/12#-Kz4c3vLWa1qY2wknvIu:-Kz4c3vLWa1qY2wknvIv:b-rv66ui) ([raw file](https://github.com/translationcoreapps/tc_resources/blob/d540220ca59b5f970caca4da1e52b7316e0db0fd/__tests__/bhpToJsonParse.test.js#L11)):*
> ```JavaScript
>  *    * Run `npm install` inside tC_resources path to install node_modules
>  *    * Run `jest __tests__/bhpToJsonParse.test.js` to download and generate bhp json files
>  *    * copy directories from __tests__/output/bhp/<version>/ to resources/grc/bibles/bhp/<version>/
> ```

this shouldn't be manual. shouldn't this happen automatically so that we don't have to copy directories?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/tc_resources/12)*

**Comment by mannycolon** [comment]
@PhotoNomad0 Let me know once your tests are done.

**Comment by PhotoNomad0** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[__tests__/bhpToJsonParse.test.js, line 11 at r4](https://reviewable.io:443/reviews/translationcoreapps/tc_resources/12#-Kz4c3vLWa1qY2wknvIu:-Kz5OFElecgta1iHfcwr:b-80zpfh) ([raw file](https://github.com/translationcoreapps/tc_resources/blob/d540220ca59b5f970caca4da1e52b7316e0db0fd/__tests__/bhpToJsonParse.test.js#L11)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

this shouldn't be manual. shouldn't this happen automatically so that we don't have to copy directories?
</blockquote></details>

Well technically this is a script that is to be run only when the bhp source files have been updated.  Was thinking that maybe this should be moved into a scripts directory.  Doing it as a test made it easy to run and to integrate checking each step of the way.  Still thinking through the best way to do this.  Maybe I could add an npm script that could run this bhp generation on demand?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/tc_resources/12)*

**Comment by PhotoNomad0** [comment]
@mannycolon ready for review

**Comment by mannycolon** [comment]
Reviewed 19 of 19 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/tc_resources/12)*

**Comment by PhotoNomad0** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[helpers/bhpHelpers.js, line 6 at r4](https://reviewable.io:443/reviews/translationcoreapps/tc_resources/12#-Kz4cWxnU3JixRqVC_GU:-KzTclHa1sHfYCg2x_HV:b-896fix) ([raw file](https://github.com/translationcoreapps/tc_resources/blob/d540220ca59b5f970caca4da1e52b7316e0db0fd/helpers/bhpHelpers.js#L6)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

we may want to create a mock API to test these methods so that we don't have to rely on removing .skip
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/tc_resources/12)*

**Pull request merged**
