### PR TITLE
WIP: Updated k- to zaln- attribute

### PR DESCRIPTION
**Pull request by mannycolon**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- Updated k- to zaln- attribute per https://github.com/unfoldingWord-dev/translationCore/issues/3781
- **Pending** `USFM-JS` **updates**
#### Please include detailed Test instructions for your pull request:
- Verify that **k-** attributes were properly replaced by **zaln-** attribute

---
This change is [Reviewable](https://reviewable.io/reviews/translationcoreapps/tc_resources/20)

### CODE REVIEW

**Comment by PhotoNomad0** [comment]
Reviewed 31 of 31 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/tc_resources/20)*

**Comment by PhotoNomad0** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/tc_resources/20#-:-L5KvaA8gz0Vjvj54APo:bnfp4nl)*

**Comment by klappy** [comment]
Reviewed 31 of 31 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/tc_resources/20)*

**Comment by klappy** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/tc_resources/20#-:-L5OrShsNe9u45MQ8CTx:bnfp4nl)*

**Pull request merged**
