### PR TITLE
WIP: toChapterFiles with tests

### PR DESCRIPTION
**Pull request by klappy**
## This PR Addresses

Adding a helper to convert a usfm file from path to json chapter files given a path.

## To Test this PR

- Run `npm install` inside `tC_resources` path to install node_modules
- Run `jest __tests__/usfmToJsonHelpers.test.js` to verify that the new tests pass to ensure functionality.

## Known issues

- All other tests are not passing, that was pre-existing and needs to be addressed in another issue.

---
This change is [Reviewable](https://reviewable.io/reviews/translationcoreapps/tc_resources/11)

### CODE REVIEW

**Comment by PhotoNomad0** [comment]
:lgtm: The new unit tests pass locally.

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/tc_resources/11#-:-Kyw-E3zsQ_Y-ozws_Tp:bnzv4fc)*

**Comment by PhotoNomad0** [comment]
Part of https://github.com/unfoldingWord-dev/translationCore/issues/3104

**Comment by richmahn** [comment]
Still a WIP?

**Comment by PhotoNomad0** [comment]
Issue handed off to me.

**Pull request closed without merging**
