### PR TITLE
Feature #2809/Add Hindi ULB for Titus

### PR DESCRIPTION
**Pull request by PhotoNomad0**
Removed bogus v0.0 for Hebrew

#### Describe what your pull request addresses (Please include relevant issue numbers):
- Added scripts and added aligned Hindi ULB resource for Titus

#### Please include detailed Test instructions for your pull request:
- should see new folder `tC_resources/resources/hi/bibles/ulb/v0/tit`.  The json files should be verseObjects.
- also changed UGNT milestone markers back to tag k

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/translationcoreapps/tc_resources/22)

### CODE REVIEW

**Comment by klappy** [comment]
*[resources/hi/bibles/ulb/v0/tit/1.json, line 6 at r1](https://reviewable.io:443/reviews/translationcoreapps/tc_resources/22#-L5pDTicCP_2JSz3tt6m:-L5pDTicCP_2JSz3tt6n:by2xppm) ([raw file](https://github.com/translationcoreapps/tc_resources/blob/e217f307c5057a9bb9cd59d7f1ee8a3cfd4d7d3f/resources/hi/bibles/ulb/v0/tit/1.json#L6)):*
> ```JSON
>       {
>         "tag": "zaln",
>         "content": "-s | x-lemma=\"Παῦλος\" x-morph=\"Gr,N,,,,,NMS,\" x-occurrence=\"1\" x-occurrences=\"1\" x-strong=\"G39720\" x-content=\"Παῦλος\"\n"
> ```

This doesn't look like it. was parsed correctly. Can you double check to see if it was a data issue or a parsing issue?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/tc_resources/22)*

**Comment by klappy** [comment]
The milestones don't appear to be parsed correctly in any of the Titus 1:1 verse as milestones.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/tc_resources/22#-:-L5pDq2E7-rTzeWUJ8wp:b-kl7nc6)*

**Comment by PhotoNomad0** [comment]
Oops - how did I miss that - updated the usfm-js version and regenerated.

---

Review status: 0 of 944 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/tc_resources/22#-:-L5q45vWP4hs3Kzgay76:bskwjy9)*

**Comment by klappy** [comment]
Reviewed 935 of 944 files at r1, 18 of 18 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/tc_resources/22)*

**Comment by klappy** [comment]
Reviewed 25 of 25 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/tc_resources/22)*

**Comment by klappy** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/tc_resources/22#-:-L5t8GxZhxY6LmCCAs9-:bnfp4nl)*

**Comment by PhotoNomad0** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[resources/hi/bibles/ulb/v0/tit/1.json, line 6 at r1](https://reviewable.io:443/reviews/translationcoreapps/tc_resources/22#-L5pDTicCP_2JSz3tt6m:-L5tC-ocyJE0PEEJ6U7k:b-rm377i) ([raw file](https://github.com/translationcoreapps/tc_resources/blob/e217f307c5057a9bb9cd59d7f1ee8a3cfd4d7d3f/resources/hi/bibles/ulb/v0/tit/1.json#L6)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

This doesn't look like it. was parsed correctly. Can you double check to see if it was a data issue or a parsing issue?
</blockquote></details>

Looks good to me (see https://git.door43.org/aniljohn/hi_tit/src/branch/master/.apps/translationCore/alignmentData/tit/1.json).  What concerns do you have?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/tc_resources/22)*

**Pull request merged**
