### PR TITLE
Bug fix #3920/fix occurrences in EN ULB 

### PR DESCRIPTION
**Pull request by PhotoNomad0**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- Fixed occurrences in EN ULB so that Greek words are aligned to closest English word.
- Updated UGNT with latest fixes such as converting “ἐgκρατῆ” to “ἐνκρατῆ”
- ran updated TW generation script to get fixed occurrence counts in TW.

#### Please include detailed Test instructions for your pull request:
- in TW the words/verses listed in issue should be aligned to closest word.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/translationcoreapps/tc_resources/25)

### CODE REVIEW

**Comment by mannycolon** [comment]
Reviewed 3 of 7 files at r1, 321 of 322 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[__tests__/englishUlbHelpers.test.js, line 8 at r2](https://reviewable.io:443/reviews/translationcoreapps/tc_resources/25#-L6rrEuzkAgMYmTW-PY6:-L6rrEuzkAgMYmTW-PY7:b-hy8n77) ([raw file](https://github.com/translationcoreapps/tc_resources/blob/c697fe94fc7ad43f2f2050b875dd03ef932a5593/__tests__/englishUlbHelpers.test.js#L8)):*
> ```JavaScript
>   const tempFilePath = './__tests__/output/en-ulb-sources';
>   const version = 'v0.0';
>   const outputFilePath = path.join('.', 'resources', 'en', 'bibles', 'ulb', version);
> ```

Do we need the dot?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/tc_resources/25)*

**Comment by mannycolon** [comment]
@PhotoNomad0 Merged with latest master branch

**Comment by mannycolon** [comment]
`Local Test: LGTM`

**Comment by mannycolon** [comment]
*[__tests__/englishUlbHelpers.test.js, line 8 at r2](https://reviewable.io:443/reviews/translationcoreapps/tc_resources/25#-L6rrEuzkAgMYmTW-PY6:-L6s-BPfDPuhCTUfl04c:b2ni8w0) ([raw file](https://github.com/translationcoreapps/tc_resources/blob/c697fe94fc7ad43f2f2050b875dd03ef932a5593/__tests__/englishUlbHelpers.test.js#L8)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

Do we need the dot?
</blockquote></details>

nvm

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/tc_resources/25)*

**Comment by richmahn** [comment]
Reviewed 3 of 7 files at r1, 321 of 322 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/tc_resources/25)*

**Pull request merged**
