### PR TITLE
Feature #3273 /Update greek resources to use UGNT

### PR DESCRIPTION
**Pull request by PhotoNomad0**
Updated grc source to UGNT and migrated to new verse objects.
 
#### testing

look at grc resources to verify using new verse object format.  Check a book from the following list to make sure that there are tw attributes for many greek words.  Not all books have tw markers, only:

* Galatians
* 1 Thessalonians
* 2 Thessalonians
* 1 Timothy
* 2 Timothy
* Titus
* Philemon

---
This change is [Reviewable](https://reviewable.io/reviews/translationcoreapps/tc_resources/15)

### CODE REVIEW

**Comment by klappy** [comment]
Spot checked lots of files and the data looks good. I didn't review each file, let alone every line.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/tc_resources/15#-:-L2M1gFiG1OnD-tquTYD:b-cndanq)*

**Comment by klappy** [comment]
Reviewed 1 of 264 files at r2.
Review status: 1 of 266 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/tc_resources/15)*

**Comment by klappy** [comment]
*[helpers/bhpHelpers.js, line 12 at r2](https://reviewable.io:443/reviews/translationcoreapps/tc_resources/15#-L2M2Dc2cAV5wXmCtSwT:-L2M2Dc3iQ0jDci3J3Lk:b-m8p0vz) ([raw file](https://github.com/translationcoreapps/tc_resources/blob/7f8f53b97836d165ed222e95efe0e3713dd2a60c/helpers/bhpHelpers.js#L12)):*
> ```JavaScript
> import assert from 'assert';
> 
> const BHP_URL = 'https://git.door43.org/Door43/UGNT/raw/master';
> ```

@jag3773: Do we need to rename this variable and all references of bhp to ugnt from this point on?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/tc_resources/15)*

**Comment by klappy** [comment]
Reviewed 1 of 264 files at r2.
Review status: 2 of 266 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/tc_resources/15)*

**Comment by PhotoNomad0** [comment]
Review status: 1 of 271 files reviewed at latest revision, 1 unresolved discussion.

---

*[helpers/ugntHelpers.js, line 12 at r2](https://reviewable.io:443/reviews/translationcoreapps/tc_resources/15#-L2M2Dc2cAV5wXmCtSwT:-L2MScoaRSgqeQBgpS59:b-896fix) ([raw file](https://github.com/translationcoreapps/tc_resources/blob/7f8f53b97836d165ed222e95efe0e3713dd2a60c/helpers/ugntHelpers.js#L12)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

@jag3773: Do we need to rename this variable and all references of bhp to ugnt from this point on?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/tc_resources/15)*

**Comment by klappy** [comment]
Reviewed 1 of 537 files at r3.
Review status: 1 of 271 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/tc_resources/15)*

**Comment by klappy** [comment]
Reviewed 536 of 537 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/tc_resources/15)*

**Comment by klappy** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/tc_resources/15#-:-L2fu0y0odGppMMjUzbo:bnfp4nl)*

**Comment by mannycolon** [comment]
Reviewed 1 of 537 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/tc_resources/15)*

**Pull request merged**
