### PR TITLE
Feature - #3912 - CODE changes - Code to sort Group Index by name

### PR DESCRIPTION
**Pull request by richmahn**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- Code changes to properly generate tW data from a given language by sorting the `index.json` file
  for a tW category based on name rather than id. Also removes the generation of the `groups` data as that is no longer generated with `translationHelpsHelpers` but in `twHelpers` from the UGNT rather than from the config.yaml.

NOTE: The content generated by this code will be in another PR for this story.

#### Please include detailed Test instructions for your pull request:
- Check out, run `npm run update-resource-form-catalog hi tW` and `npm run update-resource-form-catalog en tW`. You should see a v8 dir in `resources/en/translationHelps/translationWords` and v8.1 dir in `resources/hi/translationHelps/translationWords`. Check that the `kt/index.json` is correctly ordered in each.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/translationcoreapps/tc_resources/28)

### CODE REVIEW

**Comment by PhotoNomad0** [comment]
Reviewed 1 of 2 files at r1, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/tc_resources/28)*

**Comment by PhotoNomad0** [comment]
@richmahn - I guess I need to run `npm install -g babel-cli` before testing resource.  Why didn’t you add an npm script?

Added: babel-cli@6.26.0

But then get error:
PixelPeekerMax:tC_resources blm$ babel-node hi tW
module.js:538
    throw err;
    ^

Error: Cannot find module '/Users/blm/Development/Electron/testDir/translationCoreTest/tC_resources/hi'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Function.Module.runMain (module.js:676:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/babel-cli/lib/_babel-node.js:154:22)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
PixelPeekerMax:tC_resources blm$

**Comment by PhotoNomad0** [comment]
OK, hi works, but I could only get en to work by removing the v6 folder first.

**Comment by PhotoNomad0** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/tc_resources/28#-:-L6qJts1QGOVHKaD8FEj:bnfp4nl)*

**Comment by richmahn** [comment]
Added a npm command.

**Pull request merged**
